### ISSUE TITLE
new version of avatar stats loader no work

### ISSUE THREAD

**Issue by crimsonclientonotp** [FirEmerald/AvatarStatsLoader#6]
newest version of this mod doesnt work with bonelib 3.0.0, and patch 5. heres the errors from logging.

[14:42:25.613] [Avatar_Stats_Loader] BoneLib >= 2.0.0 detected, adding to BoneMenu
[14:42:25.614] [Avatar_Stats_Loader] System.TypeLoadException: Could not load type 'BoneLib.BoneMenu.MenuManager' from assembly 'BoneLib, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at AvatarStatsLoader.BoneMenu.StatsBoneMenu.Init()
   at AvatarStatsLoader.AvatarStatsMod.OnLateInitializeMelon() in D:\Users\test\source\repos\AvatarStatsLoader\AvatarStatsMod.cs:line 141
   at MelonLoader.MelonEvent.<>c.<Invoke>b__1_0(LemonAction x) in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\Events\MelonEvent.cs:line 174
   at MelonLoader.MelonEventBase`1.Invoke(Action`1 delegateInvoker) in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\Events\MelonEvent.cs:line 143
[14:43:30.475] [Avatar_Stats_Loader] Load mass: char_marrow1_polyBlank
[14:43:30.549] [Avatar_Stats_Loader] Load stats: char_marrow1_polyBlank
[14:43:30.551] [Avatar_Stats_Loader] Load mass: VRControllerRig
[14:43:30.551] [Avatar_Stats_Loader] Load stats: VRControllerRig
[14:43:30.553] [Avatar_Stats_Loader] Load mass: VRControllerRig
[14:43:30.553] [Avatar_Stats_Loader] Load stats: VRControllerRig
[14:43:30.664] [BoneLib] Finding player object references
[14:43:35.562] [Avatar_Stats_Loader] Load mass: VRControllerRig
[14:43:35.563] [Avatar_Stats_Loader] Load stats: VRControllerRig
[14:43:35.565] [Avatar_Stats_Loader] Load mass: VRControllerRig
[14:43:35.565] [Avatar_Stats_Loader] Load stats: VRControllerRig
[14:43:37.898] [LabFusion] Main scene 15 - Void G114 was initialized.
[14:43:44.004] [Avatar_Stats_Loader] Load mass: Draxarov
[14:43:44.005] [Avatar_Stats_Loader] Load stats: Draxarov
[14:43:44.006] [Avatar_Stats_Loader] Load mass: VRControllerRig
[14:43:44.007] [Avatar_Stats_Loader] Load stats: VRControllerRig
[14:43:44.011] [Avatar_Stats_Loader] Setting avatar to Draxarov
[14:43:44.037] [Avatar_Stats_Loader] System.MissingMethodException: Method not found: 'Il2CppSLZ.Marrow.RigManager BoneLib.Player.get_rigManager()'.
   at AvatarStatsLoader.AvatarStatsMod.RefreshAvatarStats()
   at AvatarStatsLoader.AvatarStatsMod.<OnInitializeMelon>g__refreshAvatarAct|22_1(Single prev, Single cur) in D:\Users\test\source\repos\AvatarStatsLoader\AvatarStatsMod.cs:line 72
   at MelonLoader.MelonEvent`2.<>c__DisplayClass1_0.<Invoke>b__0(LemonAction`2 x) in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\Events\MelonEvent.cs:line 192
   at MelonLoader.MelonEventBase`1.Invoke(Action`1 delegateInvoker) in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\Events\MelonEvent.cs:line 143
[14:43:44.038] [Avatar_Stats_Loader] System.MissingMethodException: Method not found: 'Il2CppSLZ.Marrow.RigManager BoneLib.Player.get_rigManager()'.
   at AvatarStatsLoader.AvatarStatsMod.RefreshAvatarStats()
   at AvatarStatsLoader.AvatarStatsMod.<OnInitializeMelon>g__refreshAvatarAct|22_1(Single prev, Single cur) in D:\Users\test\source\repos\AvatarStatsLoader\AvatarStatsMod.cs:line 72
   at MelonLoader.MelonEvent`2.<>c__DisplayClass1_0.<Invoke>b__0(LemonAction`2 x) in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\Events\MelonEvent.cs:line 192
   at MelonLoader.MelonEventBase`1.Invoke(Action`1 delegateInvoker) in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\Events\MelonEvent.cs:line 143
[14:43:44.040] [Avatar_Stats_Loader] System.MissingMethodException: Method not found: 'Il2CppSLZ.Marrow.RigManager BoneLib.Player.get_rigManager()'.
   at AvatarStatsLoader.AvatarStatsMod.RefreshAvatarStats()
   at AvatarStatsLoader.AvatarStatsMod.<OnInitializeMelon>g__refreshAvatarAct|22_1(Single prev, Single cur) in D:\Users\test\source\repos\AvatarStatsLoader\AvatarStatsMod.cs:line 72
   at MelonLoader.MelonEvent`2.<>c__DisplayClass1_0.<Invoke>b__0(LemonAction`2 x) in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\Events\MelonEvent.cs:line 192
   at MelonLoader.MelonEventBase`1.Invoke(Action`1 delegateInvoker) in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\Events\MelonEvent.cs:line 143
[14:43:44.040] [Avatar_Stats_Loader] System.MissingMethodException: Method not found: 'Il2CppSLZ.Marrow.RigManager BoneLib.Player.get_rigManager()'.
   at AvatarStatsLoader.AvatarStatsMod.RefreshAvatarStats()
   at AvatarStatsLoader.AvatarStatsMod.<OnInitializeMelon>g__refreshAvatarAct|22_1(Single prev, Single cur) in D:\Users\test\source\repos\AvatarStatsLoader\AvatarStatsMod.cs:line 72
   at MelonLoader.MelonEvent`2.<>c__DisplayClass1_0.<Invoke>b__0(LemonAction`2 x) in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\Events\MelonEvent.cs:line 192
   at MelonLoader.MelonEventBase`1.Invoke(Action`1 delegateInvoker) in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\Events\MelonEvent.cs:line 143
[14:43:44.041] [Avatar_Stats_Loader] System.MissingMethodException: Method not found: 'Il2CppSLZ.Marrow.RigManager BoneLib.Player.get_rigManager()'.
   at AvatarStatsLoader.AvatarStatsMod.RefreshAvatarStats()
   at AvatarStatsLoader.AvatarStatsMod.<OnInitializeMelon>g__refreshAvatarAct|22_1(Single prev, Single cur) in D:\Users\test\source\repos\AvatarStatsLoader\AvatarStatsMod.cs:line 72
   at MelonLoader.MelonEvent`2.<>c__DisplayClass1_0.<Invoke>b__0(LemonAction`2 x) in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\Events\MelonEvent.cs:line 192
   at MelonLoader.MelonEventBase`1.Invoke(Action`1 delegateInvoker) in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\Events\MelonEvent.cs:line 143
[14:43:44.041] [Avatar_Stats_Loader] System.MissingMethodException: Method not found: 'Il2CppSLZ.Marrow.RigManager BoneLib.Player.get_rigManager()'.
   at AvatarStatsLoader.AvatarStatsMod.RefreshAvatarStats()
   at AvatarStatsLoader.AvatarStatsMod.<OnInitializeMelon>g__refreshAvatarAct|22_1(Single prev, Single cur) in D:\Users\test\source\repos\AvatarStatsLoader\AvatarStatsMod.cs:line 72
   at MelonLoader.MelonEvent`2.<>c__DisplayClass1_0.<Invoke>b__0(LemonAction`2 x) in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\Events\MelonEvent.cs:line 192
   at MelonLoader.MelonEventBase`1.Invoke(Action`1 delegateInvoker) in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\Events\MelonEvent.cs:line 143
[14:43:44.042] [Avatar_Stats_Loader] System.MissingMethodException: Method not found: 'Il2CppSLZ.Marrow.RigManager BoneLib.Player.get_rigManager()'.
   at AvatarStatsLoader.AvatarStatsMod.RefreshAvatarStats()
   at AvatarStatsLoader.AvatarStatsMod.<OnInitializeMelon>g__refreshAvatarAct|22_1(Single prev, Single cur) in D:\Users\test\source\repos\AvatarStatsLoader\AvatarStatsMod.cs:line 72
   at MelonLoader.MelonEvent`2.<>c__DisplayClass1_0.<Invoke>b__0(LemonAction`2 x) in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\Events\MelonEvent.cs:line 192
   at MelonLoader.MelonEventBase`1.Invoke(Action`1 delegateInvoker) in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\Events\MelonEvent.cs:line 143
[14:43:44.042] [Avatar_Stats_Loader] System.MissingMethodException: Method not found: 'Il2CppSLZ.Marrow.RigManager BoneLib.Player.get_rigManager()'.
   at AvatarStatsLoader.AvatarStatsMod.RefreshAvatarStats()
   at AvatarStatsLoader.AvatarStatsMod.<OnInitializeMelon>g__refreshAvatarAct|22_1(Single prev, Single cur) in D:\Users\test\source\repos\AvatarStatsLoader\AvatarStatsMod.cs:line 72
   at MelonLoader.MelonEvent`2.<>c__DisplayClass1_0.<Invoke>b__0(LemonAction`2 x) in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\Events\MelonEvent.cs:line 192
   at MelonLoader.MelonEventBase`1.Invoke(Action`1 delegateInvoker) in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\Events\MelonEvent.cs:line 143
[14:52:18.481] [Avatar_Stats_Loader] Load mass: char_marrow1_polyBlank
[14:52:18.482] [Avatar_Stats_Loader] Load stats: char_marrow1_polyBlank
[14:52:18.483] [Avatar_Stats_Loader] Load mass: VRControllerRig
[14:52:18.483] [Avatar_Stats_Loader] Load stats: VRControllerRig
[14:52:18.484] [Avatar_Stats_Loader] Load mass: VRControllerRig
[14:52:18.484] [Avatar_Stats_Loader] Load stats: VRControllerRig
[14:52:18.495] [BoneLib] Finding player object references
[14:52:20.014] [Avatar_Stats_Loader] Load mass: Draxarov
[14:52:20.014] [Avatar_Stats_Loader] Load stats: Draxarov
[14:52:20.046] [Avatar_Stats_Loader] Load mass: VRControllerRig
[14:52:20.046] [Avatar_Stats_Loader] Load stats: VRControllerRig
[14:52:20.050] [Avatar_Stats_Loader] Setting avatar to Draxarov
[14:52:20.823] [Avatar_Stats_Loader] Load mass: VRControllerRig
[14:52:20.824] [Avatar_Stats_Loader] Load stats: VRControllerRig
[14:52:20.825] [Avatar_Stats_Loader] Load mass: VRControllerRig
[14:52:20.825] [Avatar_Stats_Loader] Load stats: VRControllerRig
[14:52:20.835] [LabFusion] Main scene Drax Range was initialized.
[15:04:26.654] [Avatar_Stats_Loader] Load mass: char_marrow1_polyBlank
[15:04:26.655] [Avatar_Stats_Loader] Load stats: char_marrow1_polyBlank
[15:04:26.656] [Avatar_Stats_Loader] Load mass: VRControllerRig
[15:04:26.657] [Avatar_Stats_Loader] Load stats: VRControllerRig
[15:04:26.657] [Avatar_Stats_Loader] Load mass: VRControllerRig
[15:04:26.658] [Avatar_Stats_Loader] Load stats: VRControllerRig
[15:04:26.662] [BoneLib] Finding player object references
[15:04:31.382] [Avatar_Stats_Loader] Load mass: Draxarov
[15:04:31.382] [Avatar_Stats_Loader] Load stats: Draxarov
[15:04:31.383] [Avatar_Stats_Loader] Load mass: VRControllerRig
[15:04:31.384] [Avatar_Stats_Loader] Load stats: VRControllerRig
[15:04:31.388] [Avatar_Stats_Loader] Setting avatar to Draxarov
[15:04:32.178] [Avatar_Stats_Loader] Load mass: VRControllerRig
[15:04:32.179] [Avatar_Stats_Loader] Load stats: VRControllerRig
[15:04:32.180] [Avatar_Stats_Loader] Load mass: VRControllerRig
[15:04:32.181] [Avatar_Stats_Loader] Load stats: VRControllerRig
[15:04:32.197] [LabFusion] Main scene Infiltration was initialized.
[15:06:55.711] [Avatar_Stats_Loader] Load mass: char_tall
[15:06:55.712] [Avatar_Stats_Loader] Load stats: char_tall
[15:06:55.714] [Avatar_Stats_Loader] Load mass: VRControllerRig
[15:06:55.715] [Avatar_Stats_Loader] Load stats: VRControllerRig
[15:06:55.720] [Avatar_Stats_Loader] Setting avatar to char_tall

**Comment by FirEmerald** [comment]
the mod was built using the other version of bonelib for patch 5. I don't even know how to begin making it work with the other available bonelib, so much has changed with the menu logic. For now, you should use the older patch 5 bonelib port.

**Comment by crimsonclientonotp** [comment]
> the mod was built using the other version of bonelib for patch 5. I don't even know how to begin making it work with the other available bonelib, so much has changed with the menu logic. For now, you should use the older patch 5 bonelib port.

The one from Adamdev or Thunderstore (the patch 5 one)? Also, the Thunderstore one (https://thunderstore.io/c/bonelab/p/crimsonteam/BoneLib_Patch_5/versions/) was updated to 3.0.0, but ill use 2.4.2 from the Patch 5 Bonelib on thunderstore till this is updated to 3.0.0.

**Comment by FirEmerald** [comment]
this one https://thunderstore.io/c/bonelab/p/funny_people/BoneLib_Patch_5_Unofficial/
Like I said before, I don't even know how to begin porting to 3.0.0 because the mod has to mess with internal bonemenu functions to do things such as the arrows that increase/decrease by different amounts.

**Comment by crimsonclientonotp** [comment]
> this one https://thunderstore.io/c/bonelab/p/funny_people/BoneLib_Patch_5_Unofficial/ Like I said before, I don't even know how to begin porting to 3.0.0 because the mod has to mess with internal bonemenu functions to do things such as the arrows that increase/decrease by different amounts.

Alr thanks.

**Comment by FirEmerald** [comment]
Alright, managed to figure it out enough to make a working version. IMO the menus don't quite look as good, but unless bonelib exposes more of the menu systems to users (I have _several_ ideas of how to make things more friendly with this), this is as good as it gets (for now)

**Comment by FirEmerald** [comment]
version has been uploaded to Thunderstore and simply awaits approval

**Comment by crimsonclientonotp** [comment]
> version has been uploaded to Thunderstore and simply awaits approval

ok thanks
