### ISSUE TITLE
Broken with BoneLib 3.1.0+, cannot load or build, Menu.CreatePage was removed

### ISSUE THREAD

**Issue by Sebby37** [FirEmerald/AvatarStatsLoader#8]
Attempting to load the latest thunderstore release I got the following error:
```log
[13:34:18.825] [Avatar_Stats_Loader] BoneLib >= 3.0.0 detected, adding to BoneMenu
[13:34:18.826] [Avatar_Stats_Loader] System.MissingMethodException: Method not found: 'BoneLib.BoneMenu.Page BoneLib.BoneMenu.Menu.CreatePage(System.String, UnityEngine.Color, Int32, Boolean)'.
   at AvatarStatsLoader.BoneMenu.StatsBoneMenu.Init()
   at AvatarStatsLoader.AvatarStatsMod.OnLateInitializeMelon()
   at MelonLoader.MelonEvent.<>c.<Invoke>b__1_0(LemonAction x) in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\Events\MelonEvent.cs:line 174
   at MelonLoader.MelonEventBase`1.Invoke(Action`1 delegateInvoker) in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\Events\MelonEvent.cs:line 143
```

I then tried building, but got the following errors building:
```
D:\Games\Bonelab\Bonelib + Fusion Compilation\AvatarStatsLoader>dotnet build
  Determining projects to restore...
  All projects are up-to-date for restore.
D:\Games\Bonelab\Bonelib + Fusion Compilation\AvatarStatsLoader\BoneMenu\MassesBoneMenu.cs(14,25): error CS0117: 'Menu' does not contain a definition for 'CreatePage' [D:\Games\Bonelab\Bonelib + Fusion Compilat
ion\AvatarStatsLoader\AvatarStatsLoader.csproj]
D:\Games\Bonelab\Bonelib + Fusion Compilation\AvatarStatsLoader\BoneMenu\StatsBoneMenu.cs(14,25): error CS0117: 'Menu' does not contain a definition for 'CreatePage' [D:\Games\Bonelab\Bonelib + Fusion Compilati
on\AvatarStatsLoader\AvatarStatsLoader.csproj]
D:\Games\Bonelab\Bonelib + Fusion Compilation\AvatarStatsLoader\BoneMenu\StatsBoneMenu.cs(10,50): warning CS0649: Field 'StatsBoneMenu.loadStats' is never assigned to, and will always have its default value nul
l [D:\Games\Bonelab\Bonelib + Fusion Compilation\AvatarStatsLoader\AvatarStatsLoader.csproj]

Build FAILED.

D:\Games\Bonelab\Bonelib + Fusion Compilation\AvatarStatsLoader\BoneMenu\StatsBoneMenu.cs(10,50): warning CS0649: Field 'StatsBoneMenu.loadStats' is never assigned to, and will always have its default value nul
l [D:\Games\Bonelab\Bonelib + Fusion Compilation\AvatarStatsLoader\AvatarStatsLoader.csproj]
D:\Games\Bonelab\Bonelib + Fusion Compilation\AvatarStatsLoader\BoneMenu\MassesBoneMenu.cs(14,25): error CS0117: 'Menu' does not contain a definition for 'CreatePage' [D:\Games\Bonelab\Bonelib + Fusion Compilat
ion\AvatarStatsLoader\AvatarStatsLoader.csproj]
D:\Games\Bonelab\Bonelib + Fusion Compilation\AvatarStatsLoader\BoneMenu\StatsBoneMenu.cs(14,25): error CS0117: 'Menu' does not contain a definition for 'CreatePage' [D:\Games\Bonelab\Bonelib + Fusion Compilati
on\AvatarStatsLoader\AvatarStatsLoader.csproj]
    1 Warning(s)
    2 Error(s)

Time Elapsed 00:00:04.61
```

After looking into the BoneLib changelog, I found the following note in their 3.1.0 release notes:
- Removed Menu.CreatePage as page creation is a responsibility given to pages

**Comment by Sebby37** [comment]
So I got bored today and decided to fix it, see: #9 😁

**Comment by DogeKingChris** [comment]
i have this same issue, how did you fix it? i dont really understand what you did in https://github.com/FirEmerald/AvatarStatsLoader/pull/9

**Comment by FirEmerald** [comment]
Fixed as of https://github.com/FirEmerald/AvatarStatsLoader/commit/308bfa94c85212d12dd7625222ddf3fd6b24f770
